1. Create a student database

In [9]:
students <- data.frame(
STUDENT_ID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
Programming_grade = c(88,72,91,78,65,85,74,82),
Math_GRADE = c(85,70,88,80,68,90,73,79),
Attendance = c(92,80,95,88,70,91,76,85),
Prerequisite = c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)
students

  STUDENT_ID Programming_grade Math_GRADE Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

2. Explore the data

In [10]:
nrow(students)
ncol(students)

max(students$Programming_grade)
max(students$Attendance)
max(students$Math_GRADE)

mean(students$Attendance)
mean(students$Math_GRADE)
mean(students$Programming_grade)

min(students$Attendance)
min(students$Math_GRADE)
min(students$Programming_grade)

[1] 8

[1] 5

[1] 91

[1] 95

[1] 90

[1] 84.625

[1] 79.125

[1] 79.375

[1] 70

[1] 68

[1] 65

In [11]:
summary(students)

     STUDENT_ID Programming_grade   Math_GRADE      Attendance
 Length   :8    Min.   :65.00     Min.   :68.00   Min.   :70.00
 N.unique :8    1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 N.blank  :0    Median :80.00     Median :79.50   Median :86.50
 Min.nchar:4    Mean   :79.38     Mean   :79.12   Mean   :84.62
 Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
                Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

3. Enter a students id

In [12]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S001
[1] "S001"

4. Search the data frames

In [13]:
student <- students[
  students$STUDENT_ID == student_id,
]
student

  STUDENT_ID Programming_grade Math_GRADE Attendance Prerequisite
1 S001       88                85         92         Yes

5. Check if students exist

In [14]:
if (nrow(student) > 0) {
  print("Found")
} else {
  print("Not Found.")
}

[1] "Found"

6. Extract student information

In [15]:
programming <- student$Programming_grade
attendance <- student$Attendance
mathGrade <- student$Math_GRADE
studentID <- student$STUDENT_ID
Prerequisite <- student$Prerequisite

cat("\nStudent ID        : ", studentID)
cat("\nProgramming Grade : ", programming)
cat("\nAttendace         : ", attendance)
cat("\nMath Grade        : ", mathGrade)
cat("\nPrerequisite      : ", Prerequisite)

Student ID        :  S001
Programming Grade :  88
Attendace         :  92
Math Grade        :  85
Prerequisite      :  Yes

7. Implement the rules

In [16]:
classify_student <- function
(programming_grade, math_grade, attendance_percentage, has_prerequisite)
{
  if (programming_grade >= 80 &&
    math_grade >= 75 &&
    attendance_percentage >= 80 &&
    has_prerequisite == "Yes")
    {
    return("Eligible")
  } else if (programming_grade >= 75 &&
    math_grade >= 70 &&
    attendance_percentage >= 75)
    {
    return("Conditionally Eligible")
  } else {
    return("Not Eligible")
  }
}

student_classification <- classify_student(programming, mathGrade, attendance, Prerequisite)
cat("Student ID:", studentID, "is", student_classification, "\n")

Student ID: S001 is Eligible

8. Apply all functions to all students

In [17]:
students$Eligibility <- mapply(classify_student,
                                   programming_grade = students$Programming_grade,
                                   math_grade = students$Math_GRADE,
                                   attendance_percentage = students$Attendance,
                                   has_prerequisite = students$Prerequisite)

print(students)

  STUDENT_ID Programming_grade Math_GRADE Attendance Prerequisite
1       S001                88         85         92          Yes
2       S002                72         70         80           No
3       S003                91         88         95          Yes
4       S004                78         80         88          Yes
5       S005                65         68         70           No
6       S006                85         90         91          Yes
7       S007                74         73         76           No
8       S008                82         79         85          Yes
             Eligibility
1               Eligible
2           Not Eligible
3               Eligible
4 Conditionally Eligible
5           Not Eligible
6               Eligible
7           Not Eligible
8               Eligible

9. create recommendation rules

In [18]:
get_recommendation <- function(eligibility) {

  if (eligibility == "Eligible") {
    return("Student may Enroll")

  } else if (eligibility == "Conditionally Eligible") { # Fixed typo here
    return("Consult Academic Adviser")

  } else {
    return("Complete requirements before enrollment")
  }
}

students$Recommendation <- sapply(
  students$Eligibility,
  get_recommendation
)

students

  STUDENT_ID Programming_grade Math_GRADE Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility            Recommendation
1 Eligible               Student may Enroll
2 Not Eligible           Complete requirements before enrollment
3 Eligible               Student may Enroll
4 Conditionally Eligible Consult Academic Adviser
5 Not Eligible           Complete requirements before enrollment
6 Eligible               Student may Enroll
7 Not Eligible           Complete requirements before enrollment
8 Eligible               Student may Enroll

EXPECTED OUTPUT

In [19]:
student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$STUDENT_ID == student_id, ] # Corrected column name

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$STUDENT_ID, "\n\n") # Corrected column name

  cat("Programming Grade:", student$Programming_grade, "\n")
  cat("Math Grade:", student$Math_GRADE, "\n")
  cat("Attendance:", student$Attendance, "%\n")
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S001

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S001

Programming Grade: 88
Math Grade: 85
Attendance: 92 %
Prerequisite: Yes

Enrollment Status:
Eligible

Recommendation:
Student may Enroll
========================================